// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtWu209zK341JmA6P81cQE1zhmwZc15Vc',
    appId: '1:82442377916:web:9be1f66f19025d86010eb9',
    messagingSenderId: '82442377916',
    projectId: 'social-app-ffd6c',
    authDomain: 'social-app-ffd6c.firebaseapp.com',
    storageBucket: 'social-app-ffd6c.appspot.com',
    measurementId: 'G-SN5KCHSJG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFXTlpUpX3Y2Ds7s-T9Taeq5owoYBfmpI',
    appId: '1:82442377916:android:3858efe429de970d010eb9',
    messagingSenderId: '82442377916',
    projectId: 'social-app-ffd6c',
    storageBucket: 'social-app-ffd6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWpchGSaUZo5TKIYAs0V6TOGJiJHgkYY4',
    appId: '1:82442377916:ios:970b32193fe0eeae010eb9',
    messagingSenderId: '82442377916',
    projectId: 'social-app-ffd6c',
    storageBucket: 'social-app-ffd6c.appspot.com',
    iosBundleId: 'com.ferdex.socialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWpchGSaUZo5TKIYAs0V6TOGJiJHgkYY4',
    appId: '1:82442377916:ios:079ce4d0d72f659c010eb9',
    messagingSenderId: '82442377916',
    projectId: 'social-app-ffd6c',
    storageBucket: 'social-app-ffd6c.appspot.com',
    iosBundleId: 'com.ferdex.socialapp.RunnerTests',
  );
}
